# Generated by Django 5.1.4 on 2026-03-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('invitation', 'Invitation'), ('deal_update', 'Deal Update'), ('task_due', 'Task Due'), ('import_complete', 'Import Complete'), ('task_assigned', 'Task Assigned')], max_length=50),
        ),
    ]
