# Generated by Django 5.1.4 on 2026-03-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('invitation', 'Invitation'), ('deal_update', 'Deal Update'), ('task_due', 'Task Due'), ('import_complete', 'Import Complete'), ('task_assigned', 'Task Assigned'), ('task_reminder', 'Task Reminder'), ('mention', 'Mention'), ('reaction', 'Reaction'), ('new_comment', 'New Comment')], max_length=50),
        ),
    ]
