from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/auth/", include("accounts.urls")),
    path("api/organizations/", include("organizations.urls")),
    path("api/contacts/import/", include("contacts.import_urls")),
    path("api/contacts/", include("contacts.urls")),
    path("api/companies/", include("companies.urls")),
    path("api/segments/", include("segments.urls")),
    path("api/pipelines/", include("deals.pipeline_urls")),
    path("api/products/", include("products.urls")),
    path("api/quotes/", include("deals.quote_urls")),
    path("api/deals/", include("deals.urls")),
    path("api/quotas/", include("deals.quota_urls")),
    path("api/pipeline-stages/", include("deals.stage_urls")),
    path("api/tasks/", include("tasks.urls")),
    path("api/timeline/", include("notes.urls")),
    path("api/notes/", include("notes.note_urls")),
    path("api/activities/", include("notes.activity_urls")),
    path("api/calls/", include("notes.call_urls")),
    path("api/chat/", include("chat.urls")),
    path("api/dashboard/", include("dashboard.urls")),
    path("api/reports/", include("reports.urls")),
    path("api/notifications/", include("notifications.urls")),
    path("api/email/", include("emails.urls")),
    path("api/search/", include("search.urls")),
    path("api/upload/", include("uploads.urls")),
    path("api/sequences/", include("sequences.urls")),
    path("api/workflows/", include("workflows.urls")),
    path("api/trash/", include("trash.urls")),
    path("api/ai-usage/", include("ai_usage.urls")),
    path("api/subscriptions/", include("subscriptions.urls")),
    path("api/webhooks/stripe/", include("subscriptions.webhook_urls")),
    path("api/invite/accept/<uuid:token>/", include("organizations.invite_urls")),
    path("api/calendar/", include("calendars.urls")),
]
