# Generated by Django 5.1.4 on 2026-03-05 19:52

from django.db import migrations


def migrate_stages_to_pipelines(apps, schema_editor):
    Pipeline = apps.get_model("deals", "Pipeline")
    PipelineStage = apps.get_model("deals", "PipelineStage")

    # Get all orgs that have stages
    org_ids = (
        PipelineStage.objects.filter(organization__isnull=False)
        .values_list("organization_id", flat=True)
        .distinct()
    )
    for org_id in org_ids:
        pipeline = Pipeline.objects.create(
            organization_id=org_id,
            name="Principal",
            is_default=True,
            order=0,
        )
        PipelineStage.objects.filter(organization_id=org_id).update(
            pipeline=pipeline
        )


def reverse_migration(apps, schema_editor):
    Pipeline = apps.get_model("deals", "Pipeline")
    PipelineStage = apps.get_model("deals", "PipelineStage")

    for stage in PipelineStage.objects.select_related("pipeline").all():
        if stage.pipeline:
            stage.organization_id = stage.pipeline.organization_id
            stage.save(update_fields=["organization_id"])

    Pipeline.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0002_alter_pipelinestage_organization_pipeline_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_stages_to_pipelines, reverse_migration),
    ]
