# Generated by Django 5.1.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0003_migrate_stages_to_pipelines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pipelinestage",
            name="organization",
        ),
        migrations.AlterField(
            model_name="pipelinestage",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="deals.pipeline",
            ),
        ),
    ]
