# Generated by Django 5.1.4 on 2026-03-06 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_quote_quoteline'),
        ('organizations', '0004_populate_organization_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStageTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('duration_in_previous', models.DurationField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='deals.deal')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='deals.pipelinestage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_transitions', to='organizations.organization')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='deals.pipelinestage')),
            ],
            options={
                'ordering': ['-transitioned_at'],
                'indexes': [models.Index(fields=['organization', 'to_stage', 'transitioned_at'], name='deals_deals_organiz_0b025d_idx'), models.Index(fields=['deal', 'transitioned_at'], name='deals_deals_deal_id_4a0fbf_idx')],
            },
        ),
    ]
