# Generated by Django 5.1.4 on 2026-03-07 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('deals', '0007_deal_deleted_at_deal_deleted_by_deal_deletion_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='companies.company'),
        ),
    ]
