# Generated by Django 5.1.4 on 2026-03-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_deal_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
    ]
