# Generated by Django 5.1.4 on 2026-03-07 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_set_is_won_is_lost_existing_stages'),
        ('organizations', '0004_populate_organization_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='loss_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deal',
            name='lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='won_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DealLossReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_loss_reasons', to='organizations.organization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='loss_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='deals.deallossreason'),
        ),
        migrations.AddConstraint(
            model_name='deallossreason',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_loss_reason_per_org'),
        ),
    ]
