# Generated by Django 5.1.4 on 2026-03-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='ai_summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='decision_role',
            field=models.CharField(blank=True, choices=[('decision_maker', 'Decideur'), ('influencer', 'Influenceur'), ('user', 'Utilisateur'), ('other', 'Autre')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='identified_needs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_score',
            field=models.CharField(blank=True, choices=[('hot', 'Chaud'), ('warm', 'Tiede'), ('cold', 'Froid')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_channel',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Telephone'), ('linkedin', 'LinkedIn'), ('other', 'Autre')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
