# Generated by Django 5.1.4 on 2026-03-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_enable_pg_trgm'),
        ('organizations', '0002_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateDetectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('match_email', models.BooleanField(default=True)),
                ('match_name', models.BooleanField(default=True)),
                ('match_phone', models.BooleanField(default=False)),
                ('match_siret', models.BooleanField(default=False)),
                ('match_company', models.BooleanField(default=False)),
                ('similarity_threshold', models.FloatField(default=0.6)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_detection_settings', to='organizations.organization')),
            ],
        ),
    ]
