# Generated by Django 5.1.4 on 2026-03-07 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0007_contact_deleted_at_contact_deleted_by_and_more'),
        ('organizations', '0004_populate_organization_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='companies.company'),
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('reports_to', 'Rend compte a'), ('manages', 'Manage'), ('assistant_of', 'Assistant de'), ('colleague', 'Collegue'), ('decision_maker', 'Decideur'), ('influencer', 'Influenceur'), ('champion', 'Champion'), ('blocker', 'Bloqueur')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='contacts.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_relationships', to='organizations.organization')),
                ('to_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='contacts.contact')),
            ],
            options={
                'unique_together': {('from_contact', 'to_contact', 'relationship_type')},
            },
        ),
    ]
