# Generated by Django 5.1.4 on 2026-03-08 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contact_company_entity_contactrelationship'),
        ('organizations', '0005_organizationsettings_scoring_hot_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='numeric_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('email_sent', 'Email envoyé'), ('email_opened', 'Email ouvert'), ('email_clicked', 'Email cliqué'), ('call_made', 'Appel effectué'), ('call_answered', 'Appel décroché'), ('deal_created', 'Deal créé'), ('deal_won', 'Deal gagné'), ('meeting', 'Réunion'), ('note_added', 'Note ajoutée'), ('task_completed', 'Tâche terminée')], max_length=30)),
                ('points', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='organizations.organization')),
            ],
            options={
                'ordering': ['event_type'],
                'unique_together': {('organization', 'event_type')},
            },
        ),
    ]
