# Generated by Django 5.1.4 on 2026-03-06 06:40

import django.db.models.deletion
import organizations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_reminder_offsets', models.JSONField(default=organizations.models.default_reminder_offsets)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
        ),
    ]
