# Generated by Django 5.1.4 on 2026-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_populate_organization_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='scoring_hot_threshold',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='scoring_warm_threshold',
            field=models.IntegerField(default=30),
        ),
    ]
