# Generated by Django 5.1.4 on 2026-03-08 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contact_company_entity_contactrelationship'),
        ('deals', '0013_populate_default_loss_reasons'),
        ('emails', '0002_emailtemplate_sentemail_template'),
        ('organizations', '0004_populate_organization_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_history_id', models.CharField(blank=True, max_length=255)),
                ('last_delta_token', models.CharField(blank=True, max_length=1000)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('error', 'Error')], default='idle', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='emails.emailaccount')),
            ],
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_thread_id', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('last_message_at', models.DateTimeField(null=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('participants', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='email_threads', to='contacts.contact')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='emails.emailaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='organizations.organization')),
            ],
            options={
                'ordering': ['-last_message_at'],
                'unique_together': {('email_account', 'provider_thread_id')},
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_message_id', models.CharField(db_index=True, max_length=255)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('from_address', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to_addresses', models.JSONField(default=list)),
                ('cc_addresses', models.JSONField(blank=True, default=list)),
                ('bcc_addresses', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('snippet', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachments_metadata', models.JSONField(blank=True, default=list)),
                ('sent_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='contacts.contact')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='deals.deal')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.emailaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='organizations.organization')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.emailthread')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['organization', '-sent_at'], name='emails_emai_organiz_3ad9bd_idx'), models.Index(fields=['contact', '-sent_at'], name='emails_emai_contact_0eba26_idx')],
                'unique_together': {('email_account', 'provider_message_id')},
            },
        ),
    ]
