PLAN_QUOTAS = {
    "solo": {
        "max_contacts": 100,
        "max_pipelines": 1,
        "max_pipeline_stages": 6,
        "max_users": 1,
        "max_ai_messages_per_month": 50,
        "features": {
            "custom_stages": False,
            "dynamic_segments": False,
            "products_catalog": False,
            "duplicate_detection": False,
            "workflows": False,
            "email_templates": False,
            "email_integration": False,
            "csv_import_export": False,
            "advanced_dashboard": False,
            "custom_reports": False,
            "conversion_funnel": False,
            "api_access": False,
            "team_assignment": False,
            "priority_support": False,
            "dedicated_onboarding": False,
        },
    },
    "pro": {
        "max_contacts": None,
        "max_pipelines": None,
        "max_pipeline_stages": None,
        "max_users": 1,
        "max_ai_messages_per_month": None,
        "features": {
            "custom_stages": True,
            "dynamic_segments": True,
            "products_catalog": True,
            "duplicate_detection": True,
            "workflows": True,
            "email_templates": True,
            "email_integration": True,
            "csv_import_export": True,
            "advanced_dashboard": True,
            "custom_reports": True,
            "conversion_funnel": True,
            "api_access": False,
            "team_assignment": False,
            "priority_support": True,
            "dedicated_onboarding": False,
        },
    },
    "team": {
        "max_contacts": None,
        "max_pipelines": None,
        "max_pipeline_stages": None,
        "max_users": None,
        "max_ai_messages_per_month": None,
        "features": {
            "custom_stages": True,
            "dynamic_segments": True,
            "products_catalog": True,
            "duplicate_detection": True,
            "workflows": True,
            "email_templates": True,
            "email_integration": True,
            "csv_import_export": True,
            "advanced_dashboard": True,
            "custom_reports": True,
            "conversion_funnel": True,
            "api_access": True,
            "team_assignment": True,
            "priority_support": True,
            "dedicated_onboarding": True,
        },
    },
}
