import uuid

REPORT_TEMPLATES = [
    {
        "name": "Performance commerciale",
        "description": "Suivi du revenu, des deals et de la performance de vente.",
        "widgets": [
            {
                "id": str(uuid.uuid4()),
                "type": "line_chart",
                "title": "Revenu par mois",
                "source": "deals",
                "metric": "sum:amount",
                "group_by": "month",
                "filters": {"date_field": "closed_at", "date_range": "last_6_months", "stage__name__in": ["Gagné"]},
                "size": "large",
            },
            {
                "id": str(uuid.uuid4()),
                "type": "bar_chart",
                "title": "Deals par stage",
                "source": "deals",
                "metric": "count",
                "group_by": "stage",
                "filters": {"date_range": "last_6_months"},
                "size": "medium",
            },
            {
                "id": str(uuid.uuid4()),
                "type": "kpi_card",
                "title": "Montant moyen des deals",
                "source": "deals",
                "metric": "avg:amount",
                "group_by": None,
                "filters": {"date_range": "last_6_months"},
                "size": "small",
            },
        ],
    },
    {
        "name": "Pipeline",
        "description": "Vue d'ensemble du pipeline et de la conversion.",
        "widgets": [
            {
                "id": str(uuid.uuid4()),
                "type": "bar_chart",
                "title": "Deals par stage",
                "source": "deals",
                "metric": "count",
                "group_by": "stage",
                "filters": {},
                "size": "large",
            },
            {
                "id": str(uuid.uuid4()),
                "type": "pie_chart",
                "title": "Valeur par stage",
                "source": "deals",
                "metric": "sum:amount",
                "group_by": "stage",
                "filters": {},
                "size": "medium",
            },
            {
                "id": str(uuid.uuid4()),
                "type": "kpi_card",
                "title": "Deals actifs",
                "source": "deals",
                "metric": "count",
                "group_by": None,
                "filters": {},
                "size": "small",
            },
        ],
    },
    {
        "name": "Activite equipe",
        "description": "Suivi des activites et des taches de l'equipe.",
        "widgets": [
            {
                "id": str(uuid.uuid4()),
                "type": "bar_chart",
                "title": "Activites par type",
                "source": "activities",
                "metric": "count",
                "group_by": "entry_type",
                "filters": {"date_range": "last_3_months"},
                "size": "large",
            },
            {
                "id": str(uuid.uuid4()),
                "type": "bar_chart",
                "title": "Taches par priorite",
                "source": "tasks",
                "metric": "count",
                "group_by": "priority",
                "filters": {},
                "size": "medium",
            },
            {
                "id": str(uuid.uuid4()),
                "type": "kpi_card",
                "title": "Taches en retard",
                "source": "tasks",
                "metric": "count",
                "group_by": None,
                "filters": {"is_done": False},
                "size": "small",
            },
        ],
    },
    {
        "name": "Contacts & Sources",
        "description": "Analyse des contacts et de leur provenance.",
        "widgets": [
            {
                "id": str(uuid.uuid4()),
                "type": "line_chart",
                "title": "Nouveaux contacts par mois",
                "source": "contacts",
                "metric": "count",
                "group_by": "month",
                "filters": {"date_range": "last_6_months"},
                "size": "large",
            },
            {
                "id": str(uuid.uuid4()),
                "type": "pie_chart",
                "title": "Repartition par source",
                "source": "contacts",
                "metric": "count",
                "group_by": "source",
                "filters": {},
                "size": "medium",
            },
            {
                "id": str(uuid.uuid4()),
                "type": "bar_chart",
                "title": "Par lead score",
                "source": "contacts",
                "metric": "count",
                "group_by": "lead_score",
                "filters": {},
                "size": "small",
            },
        ],
    },
    {
        "name": "Devis",
        "description": "Suivi des devis et du taux d'acceptation.",
        "widgets": [
            {
                "id": str(uuid.uuid4()),
                "type": "pie_chart",
                "title": "Devis par statut",
                "source": "quotes",
                "metric": "count",
                "group_by": "status",
                "filters": {},
                "size": "medium",
            },
            {
                "id": str(uuid.uuid4()),
                "type": "line_chart",
                "title": "Montant des devis par mois",
                "source": "quotes",
                "metric": "count",
                "group_by": "month",
                "filters": {"date_range": "last_6_months"},
                "size": "large",
            },
            {
                "id": str(uuid.uuid4()),
                "type": "kpi_card",
                "title": "Total devis",
                "source": "quotes",
                "metric": "count",
                "group_by": None,
                "filters": {},
                "size": "small",
            },
        ],
    },
]
