# Generated by Django 5.1.4 on 2026-03-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='entry_type',
            field=models.CharField(choices=[('contact_created', 'Contact Created'), ('deal_created', 'Deal Created'), ('deal_moved', 'Deal Moved'), ('note_added', 'Note Added'), ('task_created', 'Task Created'), ('chat_action', 'Chat Action'), ('contact_updated', 'Contact Updated'), ('call', 'Call'), ('email_sent', 'Email Sent'), ('email_received', 'Email Received'), ('meeting', 'Meeting'), ('custom', 'Custom')], max_length=50),
        ),
    ]
