# Generated by Django 5.1.4 on 2026-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_timelineentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='entry_type',
            field=models.CharField(choices=[('contact_created', 'Contact Created'), ('deal_created', 'Deal Created'), ('deal_moved', 'Deal Moved'), ('deal_updated', 'Deal Updated'), ('note_added', 'Note Added'), ('task_created', 'Task Created'), ('chat_action', 'Chat Action'), ('contact_updated', 'Contact Updated'), ('call', 'Call'), ('email_sent', 'Email Sent'), ('email_received', 'Email Received'), ('meeting', 'Meeting'), ('custom', 'Custom'), ('contact_merged', 'Contact Merged')], max_length=50),
        ),
    ]
